### PR TITLE
hyperlinks added, and a typo fix in Documentation.md

### PR DESCRIPTION
**Pull request by ozgunozerk**
Documentation.md might look really complicated.
There are only 2 changes there:
1. function declarations are now given in hyperlinks, so one can click on them and go right into the declaration in the respective file.
2. Wrong indentation fixed, resulted in nearly all lines changed. It's actually one tab that is changed

### CODE REVIEW

**Review by nazar-pc — COMMENTED** [review]
Please don't do hyperlinks to functions, they will be out of sync on any code change, it is too excessive

**Comment by ozgunozerk** [comment]
> Please don't do hyperlinks to functions, they will be out of sync on any code change, it is too excessive

I agree, however, I still believe this is the most efficient solution. Here is my train of thoughts:

Couldn't inline comment the `sloth256_189.c` since it is getting TOO chaotic. That is why, there is a separate `Documentation.md`. And in this documentation, I had to give where are these functions are defined/declared, since it really is a long file. Even with ctrl+f, it is not easy to find the function declarations because of too many occurrences. So I gave the declaration places as line numbers, as static text (originally). 

And since we were using hyperlinks, I thought these can be hyperlinks as well, why not further ease the process of the reader? And since the hyperlink and the static text near it, shares the same number, it is basically no additional effort to update the hyperlink. 

If that will be hard to maintain, so will the static text line number. We should remove both, or keep them both.

**Comment by nazar-pc** [comment]
> If that will be hard to maintain, so will the static text line number. We should remove both, or keep them both.

I do not know why line numbers were there in the first place, so yeah, I think we should remove both. Documentation is hard to maintain in general, having links on one place and code in another place makes things even more confusing when they don't match up, and will get out of sync eventually, I can almost guarantee that.

**Comment by ozgunozerk** [comment]
Ok, makes sense! Will do in next commit :)

**Review by nazar-pc — APPROVED** [review]

**Pull request merged**
